[package]
name = "reth-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
<<<<<<< HEAD
=======
workspace = true
>>>>>>> upstream/main


[dependencies]
# reth
reth-cli-runner.workspace = true
reth-chainspec.workspace = true
<<<<<<< HEAD
eyre.workspace = true

# misc
clap.workspace = true
=======

# misc
clap.workspace = true
eyre.workspace = true



>>>>>>> upstream/main
