[package]
name = "reth-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-network-types = { workspace = true, features = ["serde"] }
<<<<<<< HEAD
reth-prune-types.workspace = true
reth-stages-types.workspace = true
reth-primitives.workspace = true
=======
reth-prune-types = { workspace = true, features = ["serde"] }
reth-stages-types = { workspace = true, features = ["serde"] }
>>>>>>> upstream-v1.2.0

# serde
serde.workspace = true
humantime-serde.workspace = true

# toml
toml.workspace = true
eyre.workspace = true

[dev-dependencies]
tempfile.workspace = true
reth-network-peers.workspace = true
alloy-primitives.workspace = true
