consensus:
  enabled: true
  url: "http://beacon-chain:5052"
  name: "consensus-client"
execution:
  enabled: true
  url: "http://reth:8545"
  name: "execution-client"
  modules:
    - "eth"
    - "net"
    - "web3"