[package]
name = "reth-discv4"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Ethereum network discovery"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-net-common.workspace = true
reth-net-nat.workspace = true
reth-network-peers = { workspace = true, features = ["secp256k1"] }

# ethereum
alloy-rlp = { workspace = true, features = ["derive"] }
discv5.workspace = true
secp256k1 = { workspace = true, features = [
    "global-context",
    "rand-std",
    "recovery",
    "serde",
] }
enr.workspace = true
# async/futures
tokio = { workspace = true, features = ["io-util", "net", "time"] }
tokio-stream.workspace = true

# misc
schnellru.workspace = true
tracing.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
rand = { workspace = true, optional = true }
generic-array.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
assert_matches.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["macros"] }
reth-tracing.workspace = true

[features]
default = ["serde"]
test-utils = ["dep:rand"]
serde = ["dep:serde"]
