[package]
name = "reth-cli-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
<<<<<<< HEAD
exclude.workspace = true

[dependencies]
reth-fs-util.workspace = true
reth-network.workspace = true
reth-primitives.workspace = true
secp256k1.workspace = true
thiserror.workspace = true
eyre.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
=======

[lints]
workspace = true

[dependencies]
# reth
reth-fs-util.workspace = true

# eth
alloy-primitives.workspace = true
alloy-eips.workspace = true

secp256k1 = { workspace = true, features = ["rand"] }
rand.workspace = true

# misc
thiserror.workspace = true
eyre.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
>>>>>>> upstream/main
