[package]
name = "reth-db-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-db = { workspace = true, features = ["mdbx"] }
reth-db-api.workspace = true
reth-provider.workspace = true
reth-config.workspace = true
reth-trie.workspace = true
reth-etl.workspace = true
reth-codecs.workspace = true

# misc
eyre.workspace = true
thiserror.workspace = true

# io
serde.workspace = true
serde_json.workspace = true

# tracing
tracing.workspace = true

[lints]
workspace = true
