[package]
name = "rpc-db"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
jsonrpsee.workspace = true
reth.workspace = true
reth-db.workspace = true
reth-db-api.workspace = true
reth-node-ethereum.workspace = true
tokio = { workspace = true, features = ["full"] }
eyre.workspace = true
