[package]
name = "reth-cli-commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]

[dependencies]
reth-beacon-consensus.workspace = true
reth-chainspec.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-config.workspace = true
reth-consensus.workspace = true
reth-db = { workspace = true, features = ["mdbx"] }
reth-db-api.workspace = true
reth-db-common.workspace = true
reth-downloaders.workspace = true
<<<<<<< HEAD
=======
reth-ecies.workspace = true
reth-eth-wire.workspace = true
>>>>>>> upstream/main
reth-evm.workspace = true
reth-exex.workspace = true
reth-fs-util.workspace = true
reth-network = { workspace = true, features = ["serde"] }
reth-network-p2p.workspace = true
<<<<<<< HEAD
reth-node-core.workspace = true
=======
reth-network-peers = { workspace = true, features = ["secp256k1"] }
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-node-events.workspace = true
reth-node-metrics.workspace = true
>>>>>>> upstream/main
reth-primitives.workspace = true
reth-provider.workspace = true
reth-prune.workspace = true
reth-stages.workspace = true
reth-static-file-types.workspace = true
reth-static-file.workspace = true
reth-trie = { workspace = true, features = ["metrics"] }
<<<<<<< HEAD

tokio.workspace = true
itertools.workspace = true
=======
reth-trie-db = { workspace = true, features = ["metrics"] }

itertools.workspace = true
futures.workspace = true
tokio.workspace = true
>>>>>>> upstream/main

# misc
ahash = "0.8"
human_bytes = "0.4.1"
eyre.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
backon.workspace = true
<<<<<<< HEAD
=======
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }
>>>>>>> upstream/main

# io
fdlimit.workspace = true
confy.workspace = true
toml = { workspace = true, features = ["display"] }

# tui
comfy-table = "7.0"
crossterm = "0.27.0"
ratatui = { version = "0.27", default-features = false, features = [
    "crossterm",
] }

<<<<<<< HEAD
# metrics
metrics-process.workspace = true

=======
>>>>>>> upstream/main
# reth test-vectors
proptest = { workspace = true, optional = true }
arbitrary = { workspace = true, optional = true }
proptest-arbitrary-interop = { workspace = true, optional = true }

<<<<<<< HEAD
=======
[dev-dependencies]
reth-discv4.workspace = true

>>>>>>> upstream/main
[features]
default = []
dev = [
    "dep:proptest",
    "dep:arbitrary",
    "dep:proptest-arbitrary-interop",
    "reth-primitives/arbitrary",
    "reth-db-api/arbitrary"
]
