name: DockerHub Build & Push

on:
  push:
    branches:
      - main
      - dev
      - dockercomposeaction
      - implement-new-db-driver
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      force_build:
        type: boolean
        description: "Build image even if tests fail"
        default: false

jobs:
  docker-release:
    name: Docker Build Test Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: loadnetwork/wvm
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || (github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/main') }}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=ref,event=tag
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build local test image (single-platform)
        id: localbuild
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: wvm:local

      - name: Verify local image
        run: |
          docker image inspect wvm:local > /dev/null || {
            echo "Local image wvm:local not found!"
            exit 1
          }

      - name: Setup test environment
        run: |
          mkdir -p .testnet && chmod 750 .testnet && cd .testnet
          git clone --depth 1 https://github.com/weaveVM/wvm-docker-testnet.git .
          echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > ./execution/key.json
          chmod 600 ./execution/key.json

      - name: Run tests
        id: test
        continue-on-error: true
        run: |
          cd .testnet
          mkdir -p logs
          docker compose up -d || {
            docker compose logs > logs/compose.log
            exit 1
          }

          npm install || {
            docker compose logs > logs/compose_fail.log
            exit 1
          }

          SIGNER_KEY=${{ secrets.TEST_SIGNER_KEY }} node test.js || {
            docker compose logs > logs/compose_fail.log
            exit 1
          }

      - name: Report test status
        if: always()
        run: |
          if [ "${{ steps.test.outcome }}" == "failure" ]; then
            echo "::warning ::Tests failed but continuing due to force_build option"
            echo "### ⚠️ Test Results" >> $GITHUB_STEP_SUMMARY
            echo "Tests failed but build will continue as force_build is enabled." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Cleanup test environment
        if: always()
        run: |
          cd .testnet || true
          docker compose down || true
          cd ..
          sudo rm -rf .testnet

      - name: Push multi-arch image to DockerHub
        if: success() || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_build == 'true')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
